language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

env:
  global:
  - secure: "I+tmmAGJeSA6t1XV4LXhITr4voKYrIYh3KnvDlLLNZJTJ85u79uMGOGAW3qTSYkDX6BTbPFaUef7wP3WpLdlLVRxHa4VaoLrDp7XsOIdDlg/qsdZtloKRSKhVXVw/L/oCcJRdHAAB0KPirBwXvmHQ7G7DnYdOIfR+fYBLy2/MewBO8yUm3iCnr6BdrvxYGj4dVSdeEhH4V5Z3BnIcXwX1y3z3L7uwKz1vsW8vdI+Vn2eOly+qtZCXJynGsvF43lxHxnTRYeQl6weENTINGOKFPiPQQWjeT5iy9jRrp7x+Ev3Dflb0JcgbmptcVN2Duhwq8sH2HweCYZ1C6C7Gtj4n+QTQmKN/MkBHVopYq78NgRnvGDfKMbJtz42FCR6tLdZo4l9Rl52hLAcxVmVsn3/xzJhfiDXgsVwJWr/nsU5z1nIPA0V580usE+LF298t4T5GFoyKTSBaB9ZLgaxRDbcABG7u9ydmQrnwq8lYW4agZoJo4gWaxaOjEg5gna5bZ1Ux3qLUmv6nGdxTi40Y8DITLgYpVcilh+D74k9zLuw7W/he/29ocUw09qrfRcpg4dzUkXAC2p7mqkhgNh6NPIbbb+7U3ae7a8WPDHkC4p5/MU9prMhDfIOEGnM/lfKK3rwm2R5BvSG+NU90DdKA21Nj1N3PDT4ITEsCXR0dSTCgEk="

addons:
  sonarcloud:
    organization: "sqmio-github"
    token:
      secure: $SONAR_TOKEN

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar